version: "3.7"
services:
  front_end:
    build: ./Front-End
    ports:
    - 8080:80
  database:
    build: ./Database
    volumes:
      # - "./Database/db:/var/lib/mysql"
      - "./Database/mysqlconf:/etc/mysql/conf.d"
    # restart: always
    ports:
      - 3306:3306
    #  depends_on:
    #  - messaging
  #messaging:
  #  build: ./Messaging
  #  ports:
  #    - 5672:5672   # RabbitMQ message broker port
  #    - 15672:15672 # RabbitMQ management GUI port
  #back_end:
  #  build: ./Back-End
  #  depends_on:
  #    - messaging
  #  volumes:
  #    - "./Back-End:/usr/src/myapp"
  #db_admin:
  #  build: ./DB-Admin
  #  ports:
  #    - 8080:8080
